### ISSUE TITLE
Building benchmarks with external libraries

### ISSUE THREAD

**Issue by llogiq** [bheisler/cargo-criterion#8]
For example, `Cargo.toml`:

```toml
[package]
name = "tchbench"
version = "0.1.0"
authors = ["Andre Bogus <andre.bogus@aleph-alpha.de>"]
edition = "2018"

[dependencies]
tch = "0.1.7"
criterion = "0.3.2"

[[bench]]
name = "bench"
path = "benches/bench.rs"
harness = false
```

And `benches/bench.rs`:

```rust
use criterion::{black_box, criterion_group, criterion_main, Criterion};
use tch::Tensor;

fn bench_norm(c: &mut Criterion) {
    let t = &Tensor::of_slice(&[0_f32, 0.1f32, 0.5f32, 0.9f32]);
    c.bench_function("norm", |b| b.iter(|| black_box(t).norm()));
}

criterion_group! {
    name = benches;
    config = Criterion::default().sample_size(10);
    targets = bench_norm
}

criterion_main!(benches);
```

Running with `cargo bench` works, whereas running with `cargo criterion` fails with

```
/path/to/bench/target/release/deps/bench-6d8fcb9c538c7b9c: error while loading shared libraries: libtorch_cpu.so: cannot open shared object file: No such file or directory
Error: Non-Criterion.rs benchmark target bench exited with error code Some(127)
```
